#include "game.h"
#include "save-file.h"
#include "version.h"
#include "raylib.h"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <chrono>
#include <cstdlib>
#include <cmath>
#include <algorithm>
#include <iostream>
namespace fs=std::filesystem;
static vb::Game game;
static Color ink={25,62,54,255},paper={243,245,238,255},green={23,75,65,255},muted={82,107,99,255},line={212,222,209,255},mint={220,230,213,255},lcd={230,239,198,255},lime={212,238,129,255};
static Texture2D sprites[152];static int page=0,frames=0,dexPage=0,familyPage=0;static bool userPause=false,wasFocus=true,smoke=false,inModal=false;static std::string popup,importCandidate;static fs::path savePath,appDirectory;static bool badSave=false,saveFailed=false;static RenderTexture2D canvas;static std::string snapshot;
static double now(){return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count();}
static Vector2 mouse(){float scale=std::min(GetScreenWidth()/1040.f,GetScreenHeight()/820.f);auto m=GetMousePosition();return {(m.x-(GetScreenWidth()-1040*scale)/2)/scale,(m.y-(GetScreenHeight()-820*scale)/2)/scale};}
static void text(const std::string& s,int x,int y,int size=18,Color c=ink){DrawText(s.c_str(),x,y,size,c);}
static void box(float x,float y,float w,float h,Color c){DrawRectangleRounded({x,y,w,h},.05f,8,c);}
static void wrap(const std::string& s,int x,int y,int width,int size=17,Color color=muted){std::istringstream words(s);std::string word,row;int yy=y;while(words>>word){if(MeasureText((row+word).c_str(),size)>width&&!row.empty()){text(row,x,yy,size,color);row.clear();yy+=size+7;}row+=word+" ";}text(row,x,yy,size,color);}
static bool button(const std::string& label,float x,float y,float w,float h,bool enabled=true,bool primary=false){Rectangle r={x,y,w,h};bool hover=CheckCollisionPointRec(mouse(),r);Color c=primary?green:Color{250,252,246,255};if(hover&&enabled)c=primary?Color{37,102,87,255}:Color{233,241,222,255};box(x,y,w,h,enabled?c:Color{226,230,220,255});DrawRectangleRoundedLinesEx(r,.08f,8,1,line);int size=17;if(MeasureText(label.c_str(),size)>w-15)size=14;text(label,x+(w-MeasureText(label.c_str(),size))/2,y+(h-size)/2,size,enabled?(primary?WHITE:ink):muted);return (popup.empty()||inModal)&&enabled&&hover&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT);}
static void image(int id,int x,int y,int size){if(id>0&&id<152&&sprites[id].id)DrawTexturePro(sprites[id],{0,0,56,56},{float(x),float(y),float(size),float(size)},{0,0},0,WHITE);}
static void bar(const std::string& label,int value,int max,int x,int y,int w){text(label,x,y,15);std::string val=std::to_string(value)+" / "+std::to_string(max);text(val,x+w-MeasureText(val.c_str(),14),y,14,muted);box(x,y+24,w,7,line);box(x,y+24,w*std::clamp(value/float(std::max(1,max)),0.f,1.f),7,green);}
static std::string age(double s){return std::to_string(int(s)/3600)+"h "+std::to_string(int(s)%3600/60)+"m";}
static bool save(){
 if(badSave)return false;
 int pauseState=game.paused;game.paused=userPause;auto data=game.save();game.paused=pauseState;
 saveFailed=!vb::desktop::writeSave(savePath,data);
 if(saveFailed)popup="Could not save progress. Your previous save is kept. Export a backup from Game & saves.";
 return !saveFailed;
}
static void changed(){save();}
static void welcome(){text("EVERY ADVENTURE STARTS SMALL",45,210,16,muted);text("Who will grow with you?",45,243,32);text("Choose an egg. Set the clock. Meet your new partner.",45,287,18,muted);int ids[]={1,4,7,25,133};for(int i=0;i<5;i++){int x=45+i*192;box(x,341,180,218,WHITE);image(ids[i],x+34,360,112);if(button(vb::dex(ids[i]).name,x+10,490,160,48)){game.choose(i);badSave=false;changed();}}text("Hatch in 30 active seconds. Full chain: 72 awake hours + required levels.",45,601,18);text("Sleep, pause, minimization and closed games stop the timer.",45,635,17,muted);}
static void home(){auto&p=game.pet();if(!p.owned){welcome();return;}bool hatched=p.hatch>=30,rest=game.sleeping||game.paused;box(35,220,574,428,mint);text("VIBE / 01",61,240,18);text("VIRTUAL PARTNER SYSTEM",338,243,12,muted);box(60,278,524,269,Color{61,81,69,255});box(69,287,506,251,rest?Color{201,212,189,255}:lcd);text(hatched?vb::dex(p.id).name:"A NEW BEGINNING",85,305,19);text(hatched?"Lv. "+std::to_string(game.level()):"EGG",476,305,17);if(hatched)image(p.id,235,335+(rest?0:int(std::sin(GetTime()*2)*3)),168);else{text("?",287,345,90);text(game.clockSet?"HATCHING IN "+std::to_string(30-int(p.hatch))+" SECONDS":"SET THE CLOCK TO BEGIN",161,487,17);}if(hatched)text(game.paused?"PAUSED":game.sleeping?"SLEEPING . . .":"A little stronger, every day.",170,510,16);text((rest?"TIMER RESTING  ":"AWAKE TIME  ")+age(p.age+p.hatch),60,563,16);const char* cares[]={"Feed","Clean","Play","Train"};for(int i=0;i<4;i++)if(button(cares[i],60+i*132,596,123,40,hatched&&!rest&&!game.battle.active)){game.care(i);changed();}
 if(!game.clockSet){if(button("Set clock & hatch",35,667,190,45,true,true)){game.clockSet=1;game.message="Clock set. Your egg will hatch in 30 awake seconds.";changed();}}else if(button(game.sleeping?"Wake partner":"Sleep",35,667,175,45,!game.battle.active)){game.sleeping=!game.sleeping;changed();}
 if(button(userPause?"Resume":"Pause",232,667,175,45)){userPause=!userPause;game.paused=userPause;changed();}if(button(game.battle.active?"Resume battle":"Find a battle",429,667,180,45,hatched&&!rest,true))page=1;
 box(637,220,368,224,WHITE);text("A little everyday care",658,241,21);bar("Fullness",int(p.food),100,658,280,325);bar("Happiness",int(p.joy),100,658,329,325);bar("Freshness",int(p.clean),100,658,378,325);
 box(637,463,368,249,Color{238,243,223,255});text("THE NEXT CHAPTER",658,482,13,muted);if(game.nextId()){text(game.ready()?"Ready to evolve!":"Good things take time.",658,510,23);bar("Total awake hours",int((p.age+p.hatch)/3600),game.neededSeconds()/3600,658,554,325);bar("Evolution level",game.level(),game.neededLevel(),658,602,325);if(button("Evolve your partner",658,651,325,42,game.ready()&&!rest&&!game.battle.active,true)){if(p.id==133)popup="Choose Eevee's evolution";else{game.evolve();popup=game.message;changed();}}}else{text("Fully evolved!",658,516,27);image(p.id,770,557,112);}
}
static void battles(){auto&b=game.battle;if(game.pet().hatch<30){text("Hatch your egg before setting out.",45,250,28);if(button("Back to partner",45,310,240,48))page=0;return;}if(!b.active){text("Pick your next adventure.",45,224,30);const char* names[]={"Clover Meadow","Whispering Grove","Summit Trail","Partner League"};const char* desc[]={"A gentle start. Find your rhythm.","Stronger opponents in the trees.","A climb against evolved partners.","The toughest partners await."};int gates[]={0,3,8,15};for(int i=0;i<4;i++){int x=40+(i%2)*496,y=282+(i/2)*191;box(x,y,480,173,WHITE);text("ROUTE 0"+std::to_string(i+1),x+20,y+15,13,muted);text(names[i],x+20,y+43,25);text(desc[i],x+20,y+78,16,muted);if(button(game.wins<gates[i]?std::to_string(gates[i])+" wins to unlock":"Battle  +"+std::to_string(20+i*10)+" XP",x+20,y+112,440,43,game.wins>=gates[i]&&!game.sleeping&&!game.paused,true)){game.encounter(i);changed();}}return;}
 box(35,220,600,380,mint);text("TURN "+std::to_string(b.turn+1),58,240,15);box(57,271,556,307,lcd);text(vb::dex(b.enemy).name,80,294,22);bar("HP",b.enemyHp,b.enemyMax,80,330,280);image(b.enemy,430,284,112);image(game.pet().id,86,424,112);text(vb::dex(game.pet().id).name,276,436,22);bar("HP",b.hp,b.maxHp,276,471,305);text("Focus: "+std::to_string(b.focus)+" / 5",277,535,17);const std::string labels[]={"Tackle (+1 focus)",std::string(vb::typeName(vb::dex(game.pet().id).type))+" burst (-2 focus)","Guard (+2 focus)","Healing berry"};for(int i=0;i<4;i++){bool enabled=!game.paused&&(i!=1||b.focus>=2)&&(i!=3||b.potion);if(button(labels[i],35+(i%2)*306,618+(i/2)*52,294,44,enabled,i==1)){game.move(i);changed();if(!b.active)popup=game.message;}}
 box(660,220,345,492,WHITE);text("Make your next move.",680,246,23);wrap("Type bursts hit hard. Tackle builds focus. Guard reduces the next hit, and your berry restores half your maximum HP.",680,295,300);text("YOUR RECORD",680,426,14,muted);text(std::to_string(game.wins)+" wins / "+std::to_string(game.losses)+" losses",680,461,22);wrap("Every completed battle earns XP. Even a loss helps you grow. You return home healed.",680,505,300);if(button("Return home",680,642,300,46,!game.paused)){game.move(4);changed();}}
static void collection(){text("Your field guide.",40,221,30);int count=0;for(auto&s:vb::species)count+=game.seen[s.id];text(std::to_string(count)+" / 151 discovered",720,228,18,muted);for(int cell=0;cell<32;cell++){int i=dexPage*32+cell;if(i>=vb::speciesCount)break;auto&s=vb::species[i];int x=40+(cell%8)*122,y=268+(cell/8)*100;box(x,y,110,94,WHITE);if(game.seen[s.id])image(s.id,x+27,y+3,56);else text("?",x+43,y+12,35,line);text(game.seen[s.id]?s.name:"Unknown",x+4,y+66,12);text(std::to_string(s.id),x+4,y+5,10,muted);}if(button("Previous",40,682,170,40,dexPage>0))dexPage--;text("Page "+std::to_string(dexPage+1)+" / 5",438,693,16);if(button("Next",830,682,170,40,(dexPage+1)*32<vb::speciesCount))dexPage++;}
static void partners(){text("Choose your active partner",40,222,28);text("Wins unlock eggs. Only your selected partner grows.",40,259,17,muted);for(int cell=0;cell<15;cell++){int i=familyPage*15+cell;if(i>=vb::Families)break;int x=40+(cell%5)*195,y=300+(cell/5)*115;image(game.pets[i].id,x+65,y,56);bool enabled=game.wins>=game.unlockAt(i)&&!game.battle.active;std::string label=vb::dex(game.pets[i].id).name;if(!enabled)label+=" ("+std::to_string(game.unlockAt(i))+" wins)";if(button(label,x,y+60,182,42,enabled,game.selected==i)){game.choose(i);badSave=false;page=0;changed();}}if(button("Previous",40,670,180,40,familyPage>0))familyPage--;if(button("Back to saves",400,670,230,40))page=3;if(button("Next",820,670,180,40,(familyPage+1)*15<vb::Families))familyPage++;}
static void settings(){box(35,220,480,492,WHITE);text("Your save, your device.",58,243,25);wrap("Progress saves automatically. Export a backup to move between the browser and Windows game.",58,291,428);if(button("Export save beside the game",58,375,434,47)){int pauseState=game.paused;game.paused=userPause;auto data=game.save();game.paused=pauseState;bool exported=vb::desktop::writeSave(appDirectory/"Vibe-Beasts-export.save",data);popup=exported?"Exported Vibe-Beasts-export.save beside the game.":"Export failed. The game folder must be writable.";}if(button("Import save",58,435,434,47)){popup="Drop a .save file onto this window to import it. You will be asked before progress is replaced.";}if(button("Open save folder",58,495,434,47))OpenURL(savePath.parent_path().string().c_str());if(button("Choose partner / 79 families",58,575,434,60,!game.battle.active)){page=4;familyPage=game.selected/15;}

 box(540,220,465,492,Color{238,243,223,255});text("72 hours of growing together.",562,247,25);wrap("Full chain: 72 total awake hours, including the 30-second hatch. Three-form families evolve at 36 and 72 hours; two-form families at 72. Battles must also reach the shown level.",562,295,420);wrap("Sleep, pause, an unfocused window and closed games stop the timer. Only your selected partner grows. Care never blocks evolution. Former stone and trade evolutions need level 36. Evolving keeps your total awake time and level.",562,432,420);wrap("Pokémon Yellow sprites: The RBY Sprites Project (Plague von Karma). Unofficial fan game by agammann. No affiliation with Pokémon rights holders.",562,568,420,15);if(button("GitHub / help",562,653,420,40))OpenURL("https://github.com/agammann/vibe-beasts");}
static void frame(){
 bool focused=IsWindowFocused();if(focused!=wasFocus){game.lastTime=now();wasFocus=focused;}game.paused=userPause||!focused;game.tick(now());if(frames%120==0)save();
 if(IsFileDropped()){auto paths=LoadDroppedFiles();if(paths.count){std::string data;std::error_code ec;if(fs::file_size(paths.paths[0],ec)<=16000&&!ec){std::ifstream f(paths.paths[0],std::ios::binary);data.assign(std::istreambuf_iterator<char>(f),{});}vb::Game probe;if(data.size()<=16000&&probe.load(data)){importCandidate=data;popup="Replace current progress with this imported save?";}else popup="That file is not a valid Vibe Beasts save. Your progress is unchanged.";}UnloadDroppedFiles(paths);}
 BeginTextureMode(canvas);ClearBackground(paper);box(35,24,49,49,green);text("VB",42,37,22,lime);text("VIBE BEASTS",100,28,22);text("HATCH. HANG OUT. BATTLE. EVOLVE.",101,57,11,muted);text("Small beasts. Big vibes.",35,104,36);text(badSave?"STORED SAVE NEEDS ATTENTION":saveFailed?"SAVE UNAVAILABLE":"SAVED ON THIS DEVICE",741,120,12,muted);DrawLine(35,90,1005,90,line);
 const char* tabs[]={"01  Partner","02  Battle","03  Field guide","04  Game & saves"};for(int i=0;i<4;i++)if(button(tabs[i],35+i*243,161,231,39,true,page==i))page=i;
 if(page==0)home();else if(page==1)battles();else if(page==2)collection();else if(page==4)partners();else settings();wrap(game.message,35,738,970,16,green);text("VIBE BEASTS v" VIBE_VERSION "   /   BY AGAMMANN",35,796,11,muted);text("UNOFFICIAL POKEMON FAN GAME",773,796,11,muted);
 if(!popup.empty()){inModal=true;DrawRectangle(0,0,1040,820,Fade(ink,.83f));box(220,260,600,300,WHITE);wrap(popup,250,290,535,23,ink);if(!importCandidate.empty()){if(button("Replace save",250,478,250,50,true,true)){game.load(importCandidate);badSave=false;userPause=game.paused;importCandidate.clear();popup.clear();changed();}if(button("Cancel",518,478,270,50)){importCandidate.clear();popup.clear();}}else if(popup=="Choose Eevee's evolution"){const char* names[]={"Vaporeon","Jolteon","Flareon"};for(int i=0;i<3;i++){image(134+i,284+i*175,362,84);if(button(names[i],250+i*178,478,167,50)){game.evolve(i);popup=game.message;changed();}}}else if(button("Back to adventure",250,478,538,50,true,true))popup.clear();}
 inModal=false;EndTextureMode();BeginDrawing();ClearBackground(ink);float scale=std::min(GetScreenWidth()/1040.f,GetScreenHeight()/820.f);DrawTexturePro(canvas.texture,{0,0,1040,-820},{(GetScreenWidth()-1040*scale)/2,(GetScreenHeight()-820*scale)/2,1040*scale,820*scale},{0,0},0,WHITE);EndDrawing();frames++;
}
int main(int argc,char** argv){
 appDirectory=vb::desktop::executableDirectory();
 std::string explicitSave;
 for(int i=1;i<argc;i++){
  std::string a=argv[i];
  if(a=="--version"){if(argc!=2){std::cerr<<"Use --version alone.\n";return 2;}std::cout<<"Vibe Beasts " VIBE_VERSION "\n";return 0;}
  if(a=="--smoke-test")smoke=true;
  else if((a=="--snapshot"||a=="--save")&&i+1<argc&&argv[i+1][0]!='-'&&argv[i+1][0]!='\0'){
   if(a=="--snapshot"){snapshot=argv[++i];smoke=true;}else explicitSave=argv[++i];
  }else {std::cerr<<"Usage: VibeBeasts [--save FILE] [--smoke-test | --snapshot PNG] | --version\n";return 2;}
 }
 const char* local=std::getenv("LOCALAPPDATA");savePath=(local?fs::path(local):appDirectory)/"VibeBeasts"/"partner.save";
 if(!explicitSave.empty())savePath=fs::absolute(fs::u8path(explicitSave));else if(smoke)savePath=appDirectory/"build"/"smoke.save";
 if(!smoke&&fs::exists(savePath)){
  std::error_code ec;std::string data;
  if(fs::file_size(savePath,ec)<=16000&&!ec){std::ifstream f(savePath,std::ios::binary);data.assign(std::istreambuf_iterator<char>(f),{});}
  if(!game.load(data)){badSave=true;popup="Your stored save could not be read. It is kept unchanged. Import a valid backup or explicitly choose an egg to start a new adventure.";}
 }
 userPause=game.paused;SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_WINDOW_HIGHDPI);InitWindow(1040,820,"Vibe Beasts");auto icon=appDirectory/"icon-192.png";if(!fs::exists(icon))icon=appDirectory/"dist"/"icon-192.png";Image appIcon=LoadImage(icon.u8string().c_str());if(appIcon.data){SetWindowIcon(appIcon);UnloadImage(appIcon);}SetWindowMinSize(780,615);SetTargetFPS(60);canvas=LoadRenderTexture(1040,820);int loaded=0;for(auto&s:vb::species){std::string file="assets/";file+=(s.id<10?"00":s.id<100?"0":"");file+=std::to_string(s.id)+".png";auto sprite=appDirectory/fs::u8path(file);if(!fs::exists(sprite))sprite=appDirectory/"dist"/fs::u8path(file);if(fs::exists(sprite)){sprites[s.id]=LoadTexture(sprite.u8string().c_str());SetTextureFilter(sprites[s.id],TEXTURE_FILTER_POINT);if(sprites[s.id].id)loaded++;}}
 if(loaded!=vb::speciesCount){std::cerr<<"Missing sprites: "<<loaded<<" / "<<vb::speciesCount<<"\n";if(smoke){CloseWindow();return 2;}popup="Some sprites are missing. Extract the whole release ZIP before playing.";}
 if(smoke){game.choose(1);game.clockSet=1;game.pet().hatch=30;game.seen[4]=1;game.pet().stageAge=game.pet().age=94600;game.pet().xp=game.pet().stageXp=40;game.message="Welcome to Vibe Beasts. Your next adventure is waiting.";}
 while(!WindowShouldClose()){frame();if(smoke&&frames>=8){if(!snapshot.empty()){Image capture=LoadImageFromScreen();bool exported=ExportImage(capture,snapshot.c_str());UnloadImage(capture);if(!exported){std::cerr<<"Snapshot could not be written.\n";saveFailed=true;}}break;}}
 bool snapshotFailed=saveFailed;bool saved=save();for(auto&s:vb::species)if(sprites[s.id].id)UnloadTexture(sprites[s.id]);UnloadRenderTexture(canvas);CloseWindow();if(smoke&&(!saved||snapshotFailed))return 3;if(smoke)std::cout<<"PASS: native window, render target, "<<loaded<<" sprites, 8 frames and save\n";return 0;
}
